# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ccb713d56020726fc6baaf98ac07c61fd666cc15c2e5e2bf81f48904d9375e7347dc5c8d968654a9d7195bae61eb1c25e6a03deacee24ab62c1cb2120214a79c

test:
  secret_key_base: 1c8bc8f6d6bb538035d2b4e493cb293809b031f6a33167f01296b3ee3dcc35560a01fd1fb921132ee45a9af9145945d6587b7b40617f3d1b579f4f2df59556f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
